POST http://localhost:3000/api/authentication/login
Content-Type: application/json

{
    "email": "genius2@gmail.com",
    "password": "Password1"
}

###
GET http://localhost:3000/api/books
Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imdlbml1czJAZ21haWwuY29tIiwiaWF0IjoxNjc3MTQ3NzIzLCJleHAiOjE2NzcxNDc3NDh9.p5zVQ1zOFec0Zv-cP_vusnsCjRl8ewmuEDzgCx14S28
# Content-Type: application/json
# Authentication: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikx1dGhlciIsImlhdCI6MTY3Njg5MzIwOX0.N72RNmc6r-hWCGGwpyHJapIvhWi2mHdWaEOWBQ2CdFo

### 
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "email": "genius2@gmail.com",
    "password": "Password1",
    "name": "steen"
}

###
GET http://localhost:3000/api/register

###
POST http://localhost:3000/api/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imdlbml1czJAZ21haWwuY29tIiwiaWF0IjoxNjc3MTQ3NjIwfQ.3Afma6AglgfauUlMFXomPGPx0gKNkse181tGUKCgvNU"
}

###
DELETE http://localhost:3000/api/authentication/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imdlbml1czJAZ21haWwuY29tIiwiaWF0IjoxNjc3MTQ3NjIwfQ.3Afma6AglgfauUlMFXomPGPx0gKNkse181tGUKCgvNU"
}

###

GET http://localhost:3000/api/token

###
